name: Build Executable

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        virtualenvs-path: .venv
        installer-parallel: true

    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

    - name: Prepare build folder
      run: |
        mkdir -p build

    - name: Install dependencies
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: |
        "$(python3 -m poetry env info --path)\\Scripts\\activate.bat"
        poetry install

    - name: Install cx_Freeze
      run: |
        "$(python3 -m poetry env info --path)\\Scripts\\activate.bat"
        python setup.py build



    # - name: Install cx_Freeze
    #   run: |
    #     python3 -m pip install cx_Freeze

    # - name: Install customtkinter
    #   run: |
    #     python3 -m pip install customtkinter

    # - name: Build Executable
    #   shell: cmd
    #   run: |
    #     python setup.py build

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: build/exe.*

    - name: Update README with artifact link
      run: |
        $artifact_url="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts"
        echo "Artifact URL: $ARTIFACT_URL"
        sed -i "s|<artifact_download_link>|$ARTIFACT_URL|g" README.md

    - name: Commit and push changes to README
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add README.md
        git commit -m "Update README with artifact download link"
        git push