name: Build Executable

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "${HOME}/.local/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        poetry install

    - name: Start poetry virtual environment
      shell: bash
      run: |
        source $(poetry env info --path)/bin/activate
        echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH
        echo "PYTHONHOME=" >> $GITHUB_ENV

    - name: Prepare build folder
      run: |
        mkdir -p build

    - name: Build Executable
      run: |
        python setup.py build

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: build/exe.*
